version: "3"
services:
  webserver:
    build: ./webserver
    links:
      - db
    depends_on:
      - db
    ports:
      - "443:443"
  db:
    build: ./sqlserver
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: armbook
